import { MD3Typescale } from "react-native-paper/lib/typescript/types"

export const fonts: MD3Typescale = {
  default: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    letterSpacing: 0.25,
  },
  displaySmall: {
    fontFamily: "Roboto_400Regular",
    fontSize: 36,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 44,
  },
  displayMedium: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 45,
    letterSpacing: 0,
    lineHeight: 52,
  },
  displayLarge: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 57,
    letterSpacing: -0.25,
    lineHeight: 64,
  },
  headlineSmall: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 32,
  },
  headlineMedium: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineLarge: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
  },
  titleSmall: {
    fontFamily: "Roboto_500Medium",
    fontWeight: "500",
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  titleMedium: {
    fontFamily: "Roboto_500Medium",
    fontWeight: "500",
    fontSize: 16,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleLarge: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 22,
    letterSpacing: 0,
    lineHeight: 28,
  },
  labelSmall: {
    fontFamily: "Roboto_500Medium",
    fontWeight: "500",
    fontSize: 11,
    letterSpacing: 0.5,
    lineHeight: 17,
  },
  labelMedium: {
    fontFamily: "Roboto_500Medium",
    fontWeight: "500",
    fontSize: 12,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelLarge: {
    fontFamily: "Roboto_500Medium",
    fontWeight: "500",
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 12,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
  bodyMedium: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 14,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodyLarge: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 24,
  },
}
