<?php

return [
    'status' => [
        'color' => [
            'dialog' => [
                'IN_PREPARATION' => '#0D47A1',
                'WAITING_FOR_CLIENT_CONFIRMATION' => '#0D47A1',
                'CONTRACTOR_WAITING_FOR_CLIENT_CONFIRMATION' => '#FBC02D',
                'WAITING_FOR_CONTRACTOR_CONFIRMATION' => '#0D47A1',
                'COMMISSIONED' => '#0D47A1',
                'WAITING_FOR_CONTRACTOR_TO_START' => '#0D47A1',
                'STARTED' => '#0D47A1',
                'ONGOING' => '#0D47A1',
                'READY_FOR_REVIEW' => '#4A148C',
                'WAITING_FOR_CLIENT_REVIEW' => '#4A148C',
                'REJECT' => '#B71C1C',
                'WORK_ON_REVISIONS' => '#FF3D00',
                'WAITING_FOR_CONTRACTOR_REVISION' => '#795548',
                'FINISHED' => '#004D40',
                'FULFILLED' => '#004D40',
                'CANCELLED' => '#D50000',
            ],
            'row' => [
                'CANCELLED' => '#FFEBEE',
                'IN_PREPARATION' => '#BBDEFB',
                'WAITING_FOR_CLIENT_CONFIRMATION' => '#B3E5FC',
                'CONTRACTOR_WAITING_FOR_CLIENT_CONFIRMATION' => '#FFFDE7',
                'WAITING_FOR_CONTRACTOR_CONFIRMATION' => '#B3E5FC',
                'COMMISSIONED' => '#BBDEFB',
                'WAITING_FOR_CONTRACTOR_TO_START' => '#BBDEFB',
                'STARTED' => '#BBDEFB',
                'ONGOING' => '#BBDEFB',
                'READY_FOR_REVIEW' => '#E1BEE7',
                'WAITING_FOR_CLIENT_REVIEW' => '#E1BEE7',
                'REJECT' => '#FFCDD2',
                'WORK_ON_REVISIONS' => '#FFCCBC',
                'WAITING_FOR_CONTRACTOR_REVISION' => '#EFEBE9',
                'FINISHED' => '#B2DFDB',
                'FULFILLED' => '#B2DFDB',
            ],
        ],
        'icon' => [
            'CANCELLED' => 'highlight_off',
            'IN_PREPARATION' => 'playlist_add_check',
            'WAITING_FOR_CLIENT_CONFIRMATION' => 'pending_actions',
            'CONTRACTOR_WAITING_FOR_CLIENT_CONFIRMATION' => 'pending_actions',
            'WAITING_FOR_CONTRACTOR_CONFIRMATION' => 'manage_history',
            'COMMISSIONED' => 'warning',
            'WAITING_FOR_CONTRACTOR_TO_START' => 'pending',
            'STARTED' => 'play_arrow',
            'ONGOING' => 'play_arrow',
            'READY_FOR_REVIEW' => 'fact_check',
            'WAITING_FOR_CLIENT_REVIEW' => 'face',
            'REJECT' => 'pan_tool',
            'WORK_ON_REVISIONS' => 'restore',
            'WAITING_FOR_CONTRACTOR_REVISION' => 'update',
            'FINISHED' => 'done_all',
            'FULFILLED' => 'done_all',
        ],
    ],
];
